name: "Lint PR Title"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # use default commit-lint types as type of Pr title
          # Match against any `kebab-case` words as scopes
          scopes: |
            ^[a-z]+(?:-[a-z]+)*$

            
